# mainnet 
# ------------------------
[package]
name = "MoveSTL"
version = "1.3.0"
edition = "2024"

[dependencies]

[addresses]
move_stl =  "0xfc127e3f9318fc874f94e464b1ee06ec01da31ca85479b8ebd3fa068f11a5b7d"
